## Numpyライブラリを学習する理由

1. テクキストでは、detectMultScanの戻り値として「リストのような」と説明が省略されているが、これはNumpyのndarrayオブジェクト。
2. Numpyは画像処理、機械学習、データ分析など現在流行りの分野では必須の基礎知識である。
3. 早めに習得しておけば、非常に有効なスキルとなる。

$$
\begin{pmatrix}
   a & b \\
   c & d
\end{pmatrix}
$$
$$
\begin{pmatrix}
   1 & 2 \\
   3 & 4
\end{pmatrix}
$$
$$
\begin{pmatrix}
   1 & 2 \\
   3 & 4 \\
   5 & 6 \\
   7 & 8 
\end{pmatrix}
$$



In [ ]:
import numpy as np

np.__version__

In [ ]:
import numpy as np

# 下記のa,bがarrrayオブジェクト
a = np.array([1, 2, 3])
print(a)
b = np.array((1, 2, 3))
print(b)

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
a
type(a)
type([1, 2, 3 ,4])
a = np.array([-1, 0, 1], dtype=np.int32)
#print(a)
[1, 2, 3, 4, "abc"]
a = np.array([1, 2, 3], dtype=np.float64)
#print(a)
a = np.array([1, 0, 1], dtype=np.bool_)
#print(a)
a = np.array([[1, 2], [3, 4]], dtype = np.int32)
#print(a)
#a = np.array([[[1, 2], [3 ,4]], [[5, 6], [7, 8]]], dtype = np.int32)
#print(a, a.shape)
a = np.array([[1, 2], [3 ,4], [5, 6], [7, 8]], dtype = np.int32)
#print(a, a.shape)
#np.array([[1,2],[3]])
a = np.array([1, 2, 3, 4, 5, 6], dtype = np.int32)
#print(a)
# shapeとは行数（内側にある配列の数）と列数（内側にある配列の要素数）
a = a.reshape(2, 3)
#print(a, a.shape)
a = np.array([0, 1, 2, 3, 4, 5]).reshape(2,3)
#print(a.ravel())
a1 = np.array([0, 1, 2, 3, 4, 5])
a2 = a1.flatten()
a3 = a2.reshape(2, 3) 
a1[1] = 200
a2[1] = 300
#print(a1)
#print(a2)
#print(a3)
#print("a3のdtype =", a3.dtype)
#print("a3のshape =", a3.shape)
#print("a3のndim =", a3.ndim)
#print("a3のsize =", a3.size)
#print(np.arange(10))
#print(np.arange(0.0, 1.0, 0.2))
#print(np.linspace(0.0, 1.0, 5))
#print(np.zeros(4))
#print(np.zeros((2, 3)))
#print(np.ones(4))
print(np.random.rand(4))
print(np.random.rand(2, 3))

# map関数に引き渡すイテラブル「sample1_list」の定義
# range(5)の実行によりsample1_listの中には「0,1,2,3,4」の値が入っている
sample1_list = list(range(5))

# イテラブルを処理する関数「multi」の定義
def multi(x):
    y = x*2
    return y

# map関数を呼び出し、multi関数にイテラブルsample1_listを引き渡す
sample2_list = map(multi, sample1_list)

# multi関数からの戻り値sample2_listの値をプリントアウトして確認
print(list(sample2_list))




[0.23997742 0.23691301 0.96663275 0.00433448]
[[0.29144618 0.00107184 0.24652158]
 [0.12147645 0.80854491 0.84535836]]
[0, 2, 4, 6, 8]
