## Numpyライブラリを学習する理由

1. テクキストでは、detectMultScanの戻り値として「リストのような」と説明が省略されているが、これはNumpyのndarrayオブジェクト。
2. Numpyは画像処理、機械学習、データ分析など現在流行りの分野では必須の基礎知識である。
3. 早めに習得しておけば、非常に有効なスキルとなる。

$$
\begin{pmatrix}
   a & b \\
   c & d
\end{pmatrix}
$$
$$
\begin{pmatrix}
   1 & 2 \\
   3 & 4
\end{pmatrix}
$$
$$
\begin{pmatrix}
   1 & 2 \\
   3 & 4 \\
   5 & 6 \\
   7 & 8 
\end{pmatrix}
$$

### 内積
x = (x1, x2), y = (y1, y2) 内積 = x ・ y = x1 * y1 + x2 * y2 (スカラー（数値)になる)　　

[行列の積（掛け算）の求め方をわかりやすく解説します！](https://lab-brains.as-1.co.jp/enjoy-learn/2023/07/50258/)   



In [ ]:
import numpy as np

np.__version__

In [ ]:
import numpy as np

# 下記のa,bがarrrayオブジェクト
a = np.array([1, 2, 3])
print(a)
b = np.array((1, 2, 3))
print(b)

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
a
type(a)
type([1, 2, 3 ,4])
a = np.array([-1, 0, 1], dtype=np.int32)
#print(a)
[1, 2, 3, 4, "abc"]
a = np.array([1, 2, 3], dtype=np.float64)
#print(a)
a = np.array([1, 0, 1], dtype=np.bool_)
#print(a)
a = np.array([[1, 2], [3, 4]], dtype = np.int32)
#print(a)
#a = np.array([[[1, 2], [3 ,4]], [[5, 6], [7, 8]]], dtype = np.int32)
#print(a, a.shape)
a = np.array([[1, 2], [3 ,4], [5, 6], [7, 8]], dtype = np.int32)
#print(a, a.shape)
#np.array([[1,2],[3]])
a = np.array([1, 2, 3, 4, 5, 6], dtype = np.int32)
#print(a)
# shapeとは行数（内側にある配列の数）と列数（内側にある配列の要素数）
a = a.reshape(2, 3)
#print(a, a.shape)
a = np.array([0, 1, 2, 3, 4, 5]).reshape(2,3)
#print(a.ravel())
a1 = np.array([0, 1, 2, 3, 4, 5])
a2 = a1.flatten()
a3 = a2.reshape(2, 3) 
a1[1] = 200
a2[1] = 300
#print(a1)
#print(a2)
#print(a3)
#print("a3のdtype =", a3.dtype)
#print("a3のshape =", a3.shape)
#print("a3のndim =", a3.ndim)
#print("a3のsize =", a3.size)
#print(np.arange(10))
#print(np.arange(0.0, 1.0, 0.2))
#print(np.linspace(0.0, 1.0, 5))
#print(np.zeros(4))
#print(np.zeros((2, 3)))
#print(np.ones(4))
print(np.random.rand(4))
print(np.random.rand(2, 3))

# map関数に引き渡すイテラブル「sample1_list」の定義
# range(5)の実行によりsample1_listの中には「0,1,2,3,4」の値が入っている
sample1_list = list(range(5))

# イテラブルを処理する関数「multi」の定義
def multi(x):
    y = x*2
    return y

# map関数を呼び出し、multi関数にイテラブルsample1_listを引き渡す
sample2_list = map(multi, sample1_list)

# multi関数からの戻り値sample2_listの値をプリントアウトして確認
print(list(sample2_list))




In [ ]:
import numpy as np

a = np.arange(10)
#print(a)
a[0]
a[-1]
# Numpy 独特のインデックス
a = np.arange(10)
print("a = ", a)
b = a.reshape(2, 5)
print("b = ", b, "b.shape =", b.shape)
b[1, 3]
b[1, 3] = 1010
#print(b)
a[1:4]
a[1:]
a[:-2]
a[::2]
a[::-1]
a[1:4] = 100
#print(a)
l = [0, 1, 2, 3, 4]
#l[1:3] = 100
c = np.arange(9).reshape(3, 3)
print("c = ", c)
c[1:, 2:]
c[2:, 1:]
print("type of c = ", type(c))
print("type of l = ", type(l))


In [ ]:
import numpy as np

#for v in np.arange(10):
#    print(v, end = " / ")
#print("\n")
#a = np.arange(10)
#for v in a:
#    print(v, end = " / ")
#print("\n")
#a = np.array(["abc", "def", "ghi"])
#a

d = np.arange(9).reshape(3, 3)
print("d = ", d)
#for row in d:
#    for v in row :
#        print(v, end = " / ")
#    print("\n")

#for row in range(d.shape[0]):
#    for col in range(d.shape[1]):
#        print(d[row, col], end = " / ")
#    print("\n")

for idx, e in np.ndenumerate(d) :
    print(idx, e, end = " / ")
print("\n")

In [ ]:
import numpy as np

a = np.arange(10)
#print(" a = ", a)
#print("a + 2 = ", a + 2)
#print("a - 1 = ", a - 1)
#print("a * 2 = ", a * 2)
#print(" a / 2 = ", a / 2)
#print("a // 2 = ", a // 2)
#print("a % 2 = ", a % 2)
#print("a ** 2 = ", a ** 2)

b = np.arange(10, 20).reshape(2, 5)
print(" b = ", b)
#print("b + 2 = ", b + 2)
#print("b - 1 = ", b - 1)
#print("b * 2 = ", b * 2)
#print("b / 2 = ", b / 2)

c = np.arange(30, 40).reshape(2, 5)
print("c = ", c)
#print("b + c = ", b + c)
#print("b - c = ", b - c)
#print("b * c = ", b * c)
#print("b / c = ", b / c)
#print("b // c = ", b // c)
#print("b % c = ", b % c)
#print("b ** c = ", b ** c)

print("sqrt(c) = ", np.sqrt(c))
print("sqrt(2) = ", np.sqrt(2))

In [73]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
#print("a = ", a, ", b = ", b)
#print("a ・ b = ", np.dot(a, b))

c = np.arange(9).reshape(3, 3)
d = np.arange(9).reshape(3, 3)
print("c = ", c)
print("d = ", d)
print("c ・　d = ", np.dot(c, d))

c =  [[0 1 2]
 [3 4 5]
 [6 7 8]]
d =  [[0 1 2]
 [3 4 5]
 [6 7 8]]
c ・　d =  [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
